from core.factories.recipes.items.base import ItemRecipe
from core.factories.recipes.items.coin import CoinRecipe
from core.factories.recipes.items.ammunition import *
from core.factories.recipes.items.armor import *
from core.factories.recipes.items.containers import *
from core.factories.recipes.items.food import *
from core.factories.recipes.items.lights import *
from core.factories.recipes.items.riding import *
from core.factories.recipes.items.shields import *
from core.factories.recipes.items.survival import *
from core.factories.recipes.items.tools import *
from core.factories.recipes.items.weapons import *
from core.factories.recipes.items.writing import *
from core.factories.recipes.items.potions import *
